language: csharp

mono: none
dotnet: 1.0.4

os: linux
dist: trusty

script:
  - dotnet restore
  - dotnet build -c release
  - dotnet run Odaceo
  - dotnet publish -c release -r ubuntu.16.04-x64
  - dotnet publish -c release -r osx.10.12-x64

deploy:
  provider: bintray
  file: bintray.json
  user: ${BINTRAY_USER}
  key: ${BINTRAY_PASS}